### ISSUE TITLE
Adding user to a group suffix all previous user with the user_suffix even if it's an application

### ISSUE THREAD

**Issue by Donatien26** [InseeFrLab/sugoi-api#170]
When a user is added to a group we add the branch user suffix at the end even if there is some app-account , so the app account will then disapear from the group

**Comment by antoine-pasquale** [comment]
This issue is tagged as "bug".

So we need to know how this bug can be reproduced.

**Comment by Donatien26** [comment]
To Reproduce you will need an ldap client like apache directory studio connected to the distribution full env ldap

Go to Applications -> appliTest -> webservicesLdap_objets -> Administrateurs_WebServicesLdap in the uniquemember you will uniquemeber: uid=appli_webservicesldap,ou=Webservicesldap,ou=Applications,o=insee,c=fr

Then make a PUT request on /realms/domaine1/groups/Administrateurs_WebServicesLdap?application=WebServicesLdap with the following body {"name":"Administrateurs_WebServicesLdap","description":"Administrateurs généraux du WS gestion des contacts","users":[{"username":"appli_webservicesldap","habilitations":[],"address":{},"metadatas":{},"attributes":{}},{"username":"test_password"}]}

The go back with apache directory studio in Applications -> appliTest -> webservicesLdap_objets -> Administrateurs_WebServicesLdap in the uniquemember you will see that the uniquemember have changed for appliWebservices: uid=appli_webservicesldap,ou=contacts,ou=clients_domaine1,o=insee,c=fr

expected: Not modify the application account
