### ISSUE TITLE
Mapping Sugoi object with Ldap must be customisable

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#191]
For each realm the administrator of the application should be able to declare how to map sugoi object to the ldap instance. For example we now map *phone_number* with *telephoneNumber* but with a different ldap we might want to map it to  *phone*. Some attributes may as well be needed in an ldap and not an other. Also, we might want to have different ObjectClass corresponding to the resource (see #190 ).
The [Resource]Ldap classes serve this goal but are global and cannot be customized by an administrator.
Yet, while the way to map String to String is easy, we must have a special consideration for mapping a ldap field to a sugoi object : for instance how is *inseegroupedefaut* mapped to Habilitation ?

**Comment by micedre** [comment]
We need to do it in a way configurable by realms.

**Comment by CChemin** [comment]
I thought that we can have a property of the realm which would more or less look like that : 
```json
[{
    "sugoiName": "username",
    "ldapName": "uid"
},
{
    "sugoiMap": "attributes",
    "values": [
        {
            "sugoiMapKey": "common_names",
            "ldapName": "cn"
        },
        {
            "sugoiMapKey": "additionalMail",
            "ldapName": "inseeMailCorrespondant"
        }
    ]
},
{
    "sugoiName": "organization",
    "ldapName": "inseeOrganisationDN",
    "objectType": "organization"
},
{
    "sugoiName": "groups",
    "ldapName": "memberOf",
    "objectType": "list_group",
    "readonly": "true"
}]
```
But letting the user completely configure its realm is letting them do a lot of misconfiguration and trigger unexpected behaviours. For example we really want groups to be memberOf.
