### ISSUE TITLE
All read method on realm should apply to all userStorages

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/sugoi-api#199]
For a realm `realm1` with 2 userStorages `us1` and `us2`, with `user1` in `us1` and `user2` in `us2`, we need to be able to find both users directly with `/realms/realm1/users/user1` or `/realms/realm1/users/user2` . 

This should also be the case for organizations.

Ad a plus, it would be nice to add the information on storage and realm in user metadata.

**Comment by CChemin** [comment]
Write method without userstorage provided should also be removed.

**Comment by CChemin** [comment]
Read method should return on which userstorage the resource has been found. This information should be in the body of the response as well as in the location header.
