### ISSUE TITLE
Manifest is missing in jar distribution

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#219]
Spring boot is ill configured for jar distribution resulting in this error when launching the jar : 

```
java -jar sugoi-api-distribution/sugoi-api-distribution-jar/target/sugoi-api-distribution-jar-0.0.1-SNAPSHOT.jar
aucun attribut manifest principal dans sugoi-api-distribution/sugoi-api-distribution-jar/target/sugoi-api-distribution-jar-0.0.1-SNAPSHOT.jar
```

This is caused by the spring-boot-maven-plugin which won't launch its repackage phase. To fix this issue there are two options : 
- explicitly adding the repackage phase in the jar distribution module
```
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
            <execution>
                <goals>
                    <goal>repackage</goal>
                </goals>
            </execution>
       </executions>
      </plugin>
```

- using the spring-boot-starter-parent plugin

**Comment by Donatien26** [comment]
I believe we didn't want to depend on spring boot starter parent, so the second one is the best solution I think :)
