### ISSUE TITLE
Refactor findByProperties services for multi-userstorage paging

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#248]
It is possible to search for elements in a realm without specifying the userstorage. As it is complicated to go from one userstorage to another with pagination (for example we don't know at second request which userStorage we browsed first time) we choose to return only one page (so maybe no paging at all ?) of results. A user wanting all results must specify a userstorage or make a more specific request to have less results.

- implement findByProperties with no userstorage so that we return only one page of result
- maybe separate findByProperties with null storage and with storage for better readability
- maybe in controller for a get of multiple elements without storage return a List<Element> and not a PageResult<Element> ?
- document somewhere (swagger + general user doc ? ) the expected behaviour of a search on multiple userstorage

**Comment by Donatien26** [comment]
I think we still want a page even if it's not pageable. Otherwise we will 2 endpoints get users but which send different kind of object and it's strange I think. And not easy to use too
