### ISSUE TITLE
When 2 UserStorage have the same name Store beans are not overrided

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#25]
When we execute 
http://localhost:8080/tomcat1/v2/SSM/users?size=20&typeRecherche=et
and
http://localhost:8080/tomcat1/v2/domaine1/users?size=20&typeRecherche=et
we have the same results

**Comment by micedre** [comment]
This seems to still be the case.

**Comment by micedre** [comment]
closed by #72
