### ISSUE TITLE
Manage exchanges between a sugoi front, broker and a back

### ISSUE THREAD

**Issue by clement-dufaure** [InseeFrLab/sugoi-api#260]
## In current version :
Requests from the front sugoi are sent by the the broker to the back. The sender receive a "virtual" response of success but  which only says that the request is sent to the back. The back tries to execute but never says if success or not.
- The body of the response is in most cas directly an object "model"

## Purpose :
- Response of the front should clearly sent a more generic object of "ProviderResponse" which can contain a model object and meta-information about the way of execution
- The back should generate a broker response of type "ProviderResponse" which indicates success or not, the execption or object generated if needed

At choice :
- The back is synchronous, so it wait in the response queue of the broker the response of the resquest (pb of latencies, timeout, etc. ). If success, we have to notice the the back could not see the result, so the response shoud be a 202 for accepted but not effective
- The back don't wait and return directly a 202 which means here that the request is sent, and provide in the "ProviderResponse" whiwh can be used to request later the status of the request (pb : how to develop this endpoint without perturbate the controller model)

---

A preview of this functionnality can be seen in branch [test-broker](https://github.com/InseeFrLab/sugoi-api/tree/test-broker)

**Comment by micedre** [comment]
>     * The back is synchronous, so it wait in the response queue of the broker the response of the resquest (pb of latencies, timeout, etc. ). If success, we have to notice the the back could not see the result, so the response shoud be a 202 for accepted but not effective

How do we manage the case when the request is accepted on the broker but there is too much latency for a direct response so we don't answer with 202 but an error. In that case, the modification could still be done eventually, would it be acceptable ?

> The back don't wait and return directly a 202 which means here that the request is sent, and provide in the "ProviderResponse" whiwh can be used to request later the status of the request (pb : how to develop this endpoint without perturbate the controller model)

I think we need a transactionId in all case when we respond with 202. This transactionId could be generated by the provider. There would be 2 cases : 
* either the provider did the action completely
* either it could not
In the service we would get a ProviderResponse as said, with a status and a transactionID, wich could serve in controller to return either a 202 or another status (201 or 200).

In the controller if the same request is done with the transactionId (we ask the provider to gives detail)

This would mean : 
* in controllers, managing a new header (X-Sugoi-Transaction-ID) in response an requests (but we still return the entity model)
* in service add a method `checkStatus(TransactionId id)` and return another object than model objects (like a SugoiResponseObject with a status) in all write methods
* in provider changing the response to use SugoiResponse object with the corresponding status.
