### ISSUE TITLE
✅ Add test to credential methods on LdapStores

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#324]
As it is a critical feature, adding test seems important.
This issue leads as well to check a few behaviours that may not be normal : 
- password that are hashed are directly compare instead of hashed then compared
- there are PasswordChangeRequest in methods signatures that are not usefull
- init and reinit password do the same things
- the changepassword can be applied on a user without password by passing null
- there is no way to write password as an hashed password

**Comment by micedre** [comment]
> As it is a critical feature, adding test seems important.
> This issue leads as well to check a few behaviours that may not be normal :
> 
>     * password that are hashed are directly compare instead of hashed then compared

It should depend on the provider I think. Each stores the password in a different way, and knows how to validate it.

> 
>     * there are PasswordChangeRequest in methods signatures that are not usefull

It could be used to add some metadata available down the chain (maybe in events, or for each provider to decide on some action or others). That being said, we could use some other wayfor this.


>     * there is no way to write password as an hashed password

do you want to be able to send a hashed password when changing it ? I fear this could cause some problems for providers.

---

There has been some internal discussion, I think we are going in the foollowing direction :

sugoi api provides 2 distinct services to init or reinit a password: 
* sugoi is the one generating a new password: in this case, this new password is sent by mail on the user mail with minimal templating.
* Sugoi receives the new password directly, and stores it (maybe an option on realm to enable or disable it).

**Comment by CChemin** [comment]
> do you want to be able to send a hashed password when changing it ? I fear this could cause some problems for providers.
I was maybe thinking specifically to ldap store. There is a feature on ldap to pass a password and store it and validate it on the ldap as a hash and it is not used in the current implementation. I think it's unfortunate.
