### ISSUE TITLE
🗨️  Should app manager be reader on realm or the other way around

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/sugoi-api#331]
At the moment, being an app manager for an app on the realm gives reader permission on this realm. This implies that if the role pattern for app-manager doesn't contains a $realm part, all app manager have reader rights on all realms.

Maybe we should treat it the other way around, and gives both permission explicitly.

**Comment by CChemin** [comment]
If an appmanager try to add a user by its id without being able to read the user itself what should happen ?

**Comment by micedre** [comment]
it should work ... ?

I'm wondering if this could be a privacy concern, but I don't see how. Being an app manager meansyou can view, delete all members in the app groups, and add and Id if you know it.

This effectively means that an app manager could discover all ids in a realm (by bruteforcing...) but I think it isacceptable.

**Comment by CChemin** [comment]
Then I agree with the fact it's better to separate reader from appmanager.

**Comment by clement-dufaure** [comment]
Should usage of role like appmanger_${realm}_${application} be an alternative by putting at the same time reader and app manager ? Or definitly separate reader and app manager role ?

**Comment by micedre** [comment]
if we choose to separate the roles (and I think we should :) ), then no exceptions, even if the app_manager pattern contains a $realm part (this will only means that permission is on this particular realm and not all)
