### ISSUE TITLE
🐛 Change password type from String to Char[]

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#342]
Char[] is better to deal with password as it remains less in memory than String. The password from the user input to sending to the provider should be char[]. The char[] should be overridden after it is used.

**Comment by Donatien26** [comment]
I think it will be hard to do this without changing of library that generate password. Indeed passay library doesn't allowed to give a char[] for validating password

**Comment by micedre** [comment]
Left for later.
