### ISSUE TITLE
Use spring boot actuator

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/sugoi-api#41]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html

**Comment by micedre** [comment]
* Evaluate what can bring us spring boot actuator
* Add it in sugoi-api
* Documente how to use it

**Comment by antoine-pasquale** [comment]
Which endpoints must/should be implemented ?

**Comment by micedre** [comment]
We must implement an healthcheck.

Having some metrics (prometheus format) would be a plus, as well as some docs on how to add some functional indicator (like "user creation count"...)

It would be nice to have some info on what we can do with this library, and how to configure it.

**Comment by micedre** [comment]
Using actuator on sugoi, we need : 
* an healthcheck with a check for the config (ie "do we have a config provider available and working ?") 
* some metrics in  prometheus format (default metrics on jvm at first)
* a way to see the config (ideally without passwords)

All this should be in the module `sugoi-api-rest-commons-services`.

Those endpoints should be accessible only with an admin account, except for `/health` if we can diable details.

**Comment by antoine-pasquale** [comment]
What are the identifiers of the roles of "admin accounts" ?

Sorry to be so cautious, it is security matter.

**Comment by micedre** [comment]
It depends ont the property : 
```
fr.insee.sugoi.api.regexp.role.admin=
```
Verified by https://github.com/InseeFrLab/sugoi-api/blob/main/sugoi-api-rest-services/src/main/java/fr/insee/sugoi/services/decider/AuthorizeMethodDecider.java
