### ISSUE TITLE
Describe store interfaces

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#58]
We have to precisely describe as javadoc the expected behavior of the methods defined in WriterStore and ReaderStore for the implementations to be consistent with one another.
It's for instance lacking of information on :
* the content of the objects returned (for example do we need to have all the user's group when we retrieve a user ?)
* informations on how should be treated requests on credentials
* the possibilities of the search methods (such as what the PageableResult is expected to be or what the typeRecherche is used for)
* what should be return when not found
* the exceptions that can be thrown

**Comment by CChemin** [comment]
If a user belongs to a group but cannot be retrieved (mainly because it doesn't exist) in user source should it be added to the retrieved group or ignored ? For now a false user is created in ldap store with only the username.

**Comment by micedre** [comment]
> 
> If a user belongs to a group but cannot be retrieved (mainly because it doesn't exist) in user source should it be added to the retrieved group or ignored ? For now a false user is created in ldap store with only the username.

It should be ignored (with a warning in log)
