### ISSUE TITLE
Complete LDAP Mappers

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#74]
LDAP Mappers allow converting a java object to a ldap object and vice versa. There is a mapper for Address, Application, Group, Organization, Realm and User. For now only major or simple attributes such as the id is mapped. We need to test what the mapper can do and add missing mappings.

**Comment by CChemin** [comment]
should we add addresses as independant ldap objects or as a list of attributes directly in the user or organization ldap object ?

**Comment by micedre** [comment]
> should we add addresses as independant ldap objects or as a list of attributes directly in the user or organization ldap object ?

We want to support the existing storage, so adress as an independant object (in a branch we have to declare in userstorage config). 

In the future this will be configurable.
