### ISSUE TITLE
Retrieving and adding nested ressources when using LdapStores

### ISSUE THREAD

**Issue by CChemin** [InseeFrLab/sugoi-api#80]

**Comment by CChemin** [comment]
I'm not sure all nested resources should be written, read or used in search.
If we look at the resources User, Organization, Group and Application : Organization has sub Organization and Address, User has Organization and Address, Group has Users and Application has Groups.

When we read these resources, should : (+ when I think yes, - when I think no)
- Organization have sub Organization information (+)
- Organization have Address information (+)
- Application have all its Groups information (+)
- Group have all the information of the Users belonging to it (-)
- User have Address information (+)
- User have Organization information (+)
It may vary according to if we are retrieving a single resource or a list of resource (get by id vs search)

When we write resources, should we allow to create at the same time : 
- sub Organization for Organization (-)
- Address for Organization (+)
- Groups for Application (+)
- User for Groups (-)
- Address for User (+)
- Organization for User (-)

**Comment by micedre** [comment]
I agree with all, this may mean we will need different representations for model object (like an user with a complete organisation and a user with only id, or a link to the org)
